import type { RawListingInput } from "@/lib/ingestion/types";

/**
 * 手入力データソースのアダプタ。
 *
 * 現時点で唯一実装されているデータ取得アダプタ。SUUMO/HOME'S/アットホーム等の
 * 実サイトからの自動取得は各サイトの利用規約確認が必要なため未実装（意図的）。
 *
 * 将来、実データを取り込む場合はこのファイルと同じ形（getXxxListings(): RawListingInput[]
 * または Promise<RawListingInput[]>）で `src/lib/ingestion/sources/suumo.ts` のような
 * アダプタを追加し、呼び出し側（prisma/seed.ts や取込バッチ）でまとめて
 * ingestProperty() に渡すだけで良い。
 *
 * 物件データは STEP6 の方針に合わせ、対象地域（広島県 広島市/廿日市市/呉市/東広島市）の
 * サンプルデータに揃えてある。周辺観光地・競合件数は説明用の仮の数値であり、
 * 実際の統計・調査結果ではない。
 */
export function getManualListings(): RawListingInput[] {
  return [
    {
      name: "平和大通りレジデンス",
      prefecture: "広島県",
      city: "広島市中区",
      address: "広島県広島市中区大手町1-2-3",
      buildingType: "APARTMENT",
      rent: 118_000,
      managementFee: 8_000,
      layout: "1LDK",
      areaSqm: 36.0,
      builtYear: 2016,
      stationName: "原爆ドーム前駅",
      stationWalkMin: 5,
      hasParking: false,
      deposit: 118_000,
      keyMoney: 118_000,
      initialCost: 420_000,
      memo: "平和記念公園まで徒歩圏内。インバウンド需要が特に見込めるエリア。",
      source: "manual",
      nearbyAttractions: [
        { name: "原爆ドーム", distanceKm: 0.6 },
        { name: "平和記念公園", distanceKm: 0.8 },
        { name: "広島城", distanceKm: 1.5 },
      ],
      competitors: [
        { platform: "Airbnb", distanceKm: 0.3 },
        { platform: "Airbnb", distanceKm: 0.5 },
        { platform: "Booking.com", distanceKm: 0.9 },
      ],
    },
    {
      name: "広島城北コーポ",
      prefecture: "広島県",
      city: "広島市中区",
      address: "広島県広島市中区基町5-6",
      buildingType: "APARTMENT",
      rent: 95_000,
      managementFee: 6_000,
      layout: "1K",
      areaSqm: 26.0,
      builtYear: 2005,
      stationName: "紙屋町東駅",
      stationWalkMin: 9,
      hasParking: false,
      deposit: 95_000,
      keyMoney: 0,
      initialCost: 320_000,
      memo: "広島城・縮景園が近く、繁華街の紙屋町にもアクセスしやすい。",
      source: "manual",
      nearbyAttractions: [
        { name: "広島城", distanceKm: 0.7 },
        { name: "縮景園", distanceKm: 1.2 },
      ],
      competitors: [
        { platform: "Airbnb", distanceKm: 0.6 },
        { platform: "Airbnb", distanceKm: 1.1 },
      ],
    },
    {
      name: "宇品海岸ハウス",
      prefecture: "広島県",
      city: "広島市南区",
      address: "広島県広島市南区宇品海岸2-3-4",
      buildingType: "HOUSE",
      rent: 82_000,
      managementFee: 0,
      layout: "3DK",
      areaSqm: 68.0,
      builtYear: 1995,
      stationName: "宇品波止場町駅",
      stationWalkMin: 10,
      hasParking: true,
      deposit: 82_000,
      keyMoney: 82_000,
      initialCost: 280_000,
      memo: "宮島航路の乗り場に近く、駐車場付きの戸建て。",
      source: "manual",
      nearbyAttractions: [{ name: "広島港（宇品港）", distanceKm: 1.0 }],
      competitors: [{ platform: "Airbnb", distanceKm: 1.8 }],
    },
    {
      name: "広島駅前光町レジデンス",
      prefecture: "広島県",
      city: "広島市東区",
      address: "広島県広島市東区光町1-9-1",
      buildingType: "APARTMENT",
      rent: 88_000,
      managementFee: 5_000,
      layout: "1LDK",
      areaSqm: 34.0,
      builtYear: 2010,
      stationName: "広島駅",
      stationWalkMin: 7,
      hasParking: false,
      deposit: 88_000,
      keyMoney: 0,
      initialCost: 300_000,
      memo: "新幹線停車駅の広島駅に近く、ビジネス・観光双方の需要が見込める。",
      source: "manual",
      nearbyAttractions: [{ name: "広島城", distanceKm: 2.0 }],
      competitors: [
        { platform: "Airbnb", distanceKm: 0.4 },
        { platform: "Airbnb", distanceKm: 0.7 },
        { platform: "Booking.com", distanceKm: 0.8 },
        { platform: "Airbnb", distanceKm: 1.2 },
      ],
    },
    {
      name: "宮島口フェリーテラス",
      prefecture: "広島県",
      city: "廿日市市",
      address: "広島県廿日市市宮島口1-2-3",
      buildingType: "APARTMENT",
      rent: 72_000,
      managementFee: 4_000,
      layout: "1LDK",
      areaSqm: 32.0,
      builtYear: 2013,
      stationName: "宮島口駅",
      stationWalkMin: 4,
      hasParking: true,
      deposit: 72_000,
      keyMoney: 72_000,
      initialCost: 260_000,
      memo: "宮島への玄関口。フェリー乗り場まで徒歩圏内で外国人観光客に人気のエリア。",
      source: "manual",
      nearbyAttractions: [
        { name: "宮島（嚴島神社）", distanceKm: 1.2 },
        { name: "宮島水族館", distanceKm: 2.5 },
      ],
      competitors: [
        { platform: "Airbnb", distanceKm: 0.5 },
        { platform: "Airbnb", distanceKm: 1.0 },
      ],
    },
    {
      name: "宮島みやじま古民家の宿",
      prefecture: "広島県",
      city: "廿日市市",
      address: "広島県廿日市市宮島町4-5",
      buildingType: "HOUSE",
      rent: 68_000,
      managementFee: 0,
      layout: "2DK",
      areaSqm: 55.0,
      builtYear: 1980,
      stationName: "宮島桟橋",
      stationWalkMin: 8,
      hasParking: false,
      deposit: 68_000,
      keyMoney: 0,
      initialCost: 240_000,
      memo: "嚴島神社まで徒歩圏内の古民家。改装次第で高付加価値な宿泊体験を提供できる。",
      source: "manual",
      nearbyAttractions: [
        { name: "嚴島神社", distanceKm: 0.5 },
        { name: "弥山（宮島ロープウエー）", distanceKm: 2.8 },
      ],
      competitors: [
        { platform: "Airbnb", distanceKm: 0.2 },
        { platform: "Airbnb", distanceKm: 0.4 },
        { platform: "Airbnb", distanceKm: 0.6 },
      ],
    },
    {
      name: "廿日市中央コーポ",
      prefecture: "広島県",
      city: "廿日市市",
      address: "広島県廿日市市天神1-2",
      buildingType: "APARTMENT",
      rent: 60_000,
      managementFee: 3_000,
      layout: "2LDK",
      areaSqm: 50.0,
      builtYear: 2001,
      stationName: "廿日市市役所前駅",
      stationWalkMin: 12,
      hasParking: true,
      deposit: 60_000,
      keyMoney: 0,
      initialCost: 220_000,
      memo: "宮島から少し離れているが家賃を抑えられ、駐車場もあり車移動の宿泊客に向く。",
      source: "manual",
      nearbyAttractions: [{ name: "宮島（嚴島神社）", distanceKm: 5.5 }],
      competitors: [{ platform: "Airbnb", distanceKm: 2.0 }],
    },
    {
      name: "呉本通りマンション",
      prefecture: "広島県",
      city: "呉市",
      address: "広島県呉市本通4-5-6",
      buildingType: "APARTMENT",
      rent: 65_000,
      managementFee: 4_000,
      layout: "1LDK",
      areaSqm: 33.0,
      builtYear: 2008,
      stationName: "呉駅",
      stationWalkMin: 6,
      hasParking: false,
      deposit: 65_000,
      keyMoney: 65_000,
      initialCost: 240_000,
      memo: "大和ミュージアムまで徒歩圏内で、呉駅からのアクセスも良好。",
      source: "manual",
      nearbyAttractions: [
        { name: "大和ミュージアム", distanceKm: 0.8 },
        { name: "てつのくじら館", distanceKm: 0.9 },
      ],
      competitors: [{ platform: "Airbnb", distanceKm: 0.7 }],
    },
    {
      name: "音戸の瀬戸ビューハウス",
      prefecture: "広島県",
      city: "呉市",
      address: "広島県呉市音戸町北隠渡1-2",
      buildingType: "HOUSE",
      rent: 55_000,
      managementFee: 0,
      layout: "3LDK",
      areaSqm: 78.0,
      builtYear: 1990,
      stationName: "呉駅",
      stationWalkMin: 25,
      hasParking: true,
      deposit: 55_000,
      keyMoney: 0,
      initialCost: 210_000,
      memo: "音戸の瀬戸を望む高台の戸建て。車前提の立地だが駐車場あり。",
      source: "manual",
      nearbyAttractions: [{ name: "音戸の瀬戸", distanceKm: 1.0 }],
      competitors: [],
    },
    {
      name: "呉中央通りステイ",
      prefecture: "広島県",
      city: "呉市",
      address: "広島県呉市中央3-1-1",
      buildingType: "APARTMENT",
      rent: 58_000,
      managementFee: 3_500,
      layout: "1K",
      areaSqm: 24.0,
      builtYear: 2000,
      stationName: "呉駅",
      stationWalkMin: 8,
      hasParking: false,
      deposit: 58_000,
      keyMoney: 0,
      initialCost: 200_000,
      memo: "海上自衛隊呉基地・大和ミュージアムに近く、ビジネス需要も見込める。",
      source: "manual",
      nearbyAttractions: [{ name: "大和ミュージアム", distanceKm: 1.4 }],
      competitors: [
        { platform: "Airbnb", distanceKm: 0.5 },
        { platform: "Airbnb", distanceKm: 1.1 },
      ],
    },
    {
      name: "西条酒蔵通りコーポ",
      prefecture: "広島県",
      city: "東広島市",
      address: "広島県東広島市西条本町5-6",
      buildingType: "APARTMENT",
      rent: 62_000,
      managementFee: 4_000,
      layout: "1LDK",
      areaSqm: 35.0,
      builtYear: 2012,
      stationName: "西条駅",
      stationWalkMin: 6,
      hasParking: true,
      deposit: 62_000,
      keyMoney: 62_000,
      initialCost: 230_000,
      memo: "酒蔵通りに近く、酒蔵見学ツアー客の宿泊需要が見込める。",
      source: "manual",
      nearbyAttractions: [
        { name: "西条酒蔵通り", distanceKm: 0.4 },
        { name: "賀茂鶴酒造", distanceKm: 0.5 },
      ],
      competitors: [{ platform: "Airbnb", distanceKm: 0.6 }],
    },
    {
      name: "東広島大学通りハウス",
      prefecture: "広島県",
      city: "東広島市",
      address: "広島県東広島市鏡山3-4-5",
      buildingType: "HOUSE",
      rent: 58_000,
      managementFee: 0,
      layout: "4LDK",
      areaSqm: 95.0,
      builtYear: 1997,
      stationName: "西条駅",
      stationWalkMin: 20,
      hasParking: true,
      deposit: 58_000,
      keyMoney: 0,
      initialCost: 210_000,
      memo: "広島大学に近く、学会・大学関連の中長期滞在需要が見込める広めの戸建て。",
      source: "manual",
      nearbyAttractions: [{ name: "龍王山", distanceKm: 2.2 }],
      competitors: [],
    },
  ];
}
